FROM nvidia/cuda:11.8.0-cudnn8-devel-ubuntu22.04


# baseline
RUN apt-get update
RUN apt-get install -y python3 python3-pip python3-setuptools


# ubuntu package dependencies
# libsm6 libxext6 libxrender1 : needed by opencv
# cmake protobuf-compiler libprotoc-dev : needed by onnx
# graphviz : needed by tvm
# swig : needed by model selection tool
# curl vim git wget gdb : needeed by baseline dev


COPY Miniconda3-latest-Linux-x86_64.sh /Miniconda3-latest-Linux-x86_64.sh

RUN bash -c 'apt-get update;\
                apt-get install -y cmake libprotobuf-dev protobuf-compiler libprotoc-dev graphviz swig curl vim git wget gdb nano zip pkg-config libgtk-3-dev libyaml-cpp-dev ffmpeg;'

